# Install brew
if [ ! -f /opt/homebrew/bin/brew ]; then
  echo "Homebrew not found. Installing Homebrew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi
eval "$(/opt/homebrew/bin/brew shellenv)"

# Install lsd
if ! command -v lsd &> /dev/null; then
    echo "'lsd' is not installed. Installing via Homebrew..."
    brew install lsd
fi

export EDITOR=nvim
export GOPATH='/usr/local/go/bin'
export PATH_TO_FX='~/Java/javafx-sdk-11.0.2/lib'
export PATH_TO_FX_MODS='~/Java/javafx-sdk-11.0.2/lib'
export PATH="/Applications/snap/bin:$PATH"

alias vi='vim'
alias vim='nvim'
alias pip='pip3'
alias python='python3'
alias activate='source venv/bin/activate'
alias ls='lsd -l'
alias lso='ls'

alias gd='git diff'
alias gs='git status'
alias gst='git status ./'
alias gdc='git diff --cached'
alias gdch='git diff --cached ./'
alias gdh='git diff ./'
alias gac='git add-commit'
alias ga='git add'
alias gaa='git add .'
alias gc='git commit'
alias gpo='git push origin'
alias gp='git push'
alias gpl='git pull'
alias gr='git reset'
alias grh='git reset --hard'
alias gb='git branch'
alias gco='git checkout'
alias grf='git checkout --'
alias gclean='git branch | grep -v "main" | xargs git branch -D'

alias crpdb='cloud-sql-proxy --address 0.0.0.0 --port 5432 all-services-dev-5589:northamerica-northeast1:crp-database'
alias gclogin='gcloud auth application-default login'

source $(brew --prefix)/share/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/opt/homebrew/bin/google-cloud-sdk/path.zsh.inc' ]; then . '/opt/homebrew/bin/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/opt/homebrew/bin/google-cloud-sdk/completion.zsh.inc' ]; then . '/opt/homebrew/bin/google-cloud-sdk/completion.zsh.inc'; fi

export PATH="/opt/homebrew/opt/postgresql@15/bin:$PATH"
